CREATE TABLE `Config` (
  `id` int NOT NULL AUTO_INCREMENT,
  `Cliente` int NOT NULL,
  `ModuloId` varchar(45) NOT NULL,
  `Model` varchar(45) NOT NULL,
  `Videoteste` varchar(45) DEFAULT NULL,
  `SetTeste` int NOT NULL DEFAULT '0',
  `SetDebug` int NOT NULL DEFAULT '0',
  `TentativasDeAcessoInternet` int NOT NULL DEFAULT '0',
  `BaseLDR` int NOT NULL DEFAULT '0',
  `BaseHR` int NOT NULL DEFAULT '0',
  `BaseUmidade` int NOT NULL DEFAULT '0',
  `BaseTemperatura` int NOT NULL DEFAULT '0',
  `BaseBuzzer` int NOT NULL DEFAULT '0',
  `BaseGyro` int NOT NULL DEFAULT '0',
  `BaseIluminacao` int NOT NULL DEFAULT '0',
  `Idioma` varchar(45) NOT NULL,
  `Versao` varchar(45) DEFAULT 'pt-br',
  `Serial` text NOT NULL,
  `LinePosition` int DEFAULT '250',
  `FAZER_TESTE` varchar(10) DEFAULT 'False',
  `MODO` varchar(10) DEFAULT 'no_rb',
  `verificar_dependencias` varchar(10) DEFAULT 'False',
  `tipo_video` varchar(255) DEFAULT 'video_interno',
  `camera_usb_index` int DEFAULT '0',
  `db_path_local` text,
  `db_name_local` text,
  `Classes` text,
  `Status` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_clientes_idx` (`Cliente`),
  KEY `fk_Config_Clientes_idx` (`Cliente`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
